/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.5/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    id("application")
    id("com.diffplug.spotless").version("6.23.3")
    id("pmd")
}

repositories {
    mavenCentral()
}

dependencies {
    testImplementation(libs.junit.jupiter)
    testRuntimeOnly("org.junit.platform:junit-platform-launcher")
    implementation(libs.guava)
}

application { mainClass.set("aoc.Main") }

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(17))
    }
}

spotless {
    java {
        importOrder()
        removeUnusedImports()
        palantirJavaFormat()
    }
}

pmd {
    toolVersion = "6.55.0"
    sourceSets = listOf(pmd.sourceSets.find { it.name == SourceSet.MAIN_SOURCE_SET_NAME })
    ruleSetFiles = files("./.myJankConfigFiles/pmd-disable-some-rules.xml")
}


tasks.named<Test>("test") { useJUnitPlatform() }
tasks.compileJava {
    dependsOn(tasks.spotlessApply)
}
